### ISSUE TITLE
Bad pointers to MS in Spine

### ISSUE THREAD

**Issue by zmbq** [FrankensteinVariorum/fv-data#18] opened 2019-07-04 13:06 UTC
Bad pointers in chunk 7:

```
﻿index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0009']/tei:zone[@type='main']//tei:line[22] returned more than one node
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0009']/tei:zone[@type='main']//tei:line[23] returned more than one node
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0009']/tei:zone[@type='main']//tei:line[24] returned more than one node
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0009']/tei:zone[@type='main']//tei:line[25] returned more than one node
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0009']/tei:zone[@type='main']//tei:line[26] returned more than one node
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0009']/tei:zone[@type='main']//tei:line[27] returned more than one node
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0009']/tei:zone[@type='main']//tei:line[28] returned more than one node
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0015']/tei:zone[@type='main']//tei:line[15] returned more than one node
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0015']/tei:zone[@type='main']//tei:line[16] returned more than one node
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0015']/tei:zone[@type='main']//tei:line[17] returned more than one node
2
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0015']/tei:zone[@type='main']//tei:line[18] returned more than one node
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0015']/tei:zone[@type='main']//tei:line[19] returned more than one node
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0015']/tei:zone[@type='main']//tei:line[20] returned more than one node
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0015']/tei:zone[@type='main']//tei:line[22] returned more than one node
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0015']/tei:zone[@type='main']//tei:line[23] returned more than one node
2
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0015']/tei:zone[@type='main']//tei:line[25] returned more than one node
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0015']/tei:zone[@type='main']//tei:line[27] returned more than one node
2
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0015']/tei:zone[@type='main']//tei:line[28] returned more than one node
3
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0015']/tei:zone[@type='main']//tei:line[30] returned more than one node
index.js:1375 Pointer <ptr xmlns="http://www.tei-c.org/ns/1.0" target="https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/fMS_C07.xml#,1,2)"/> is invalid
index.js:1375 Pointer <ptr xmlns="http://www.tei-c.org/ns/1.0" target="https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/fMS_C07.xml#,1,3)"/> is invalid
index.js:1375 Pointer <ptr xmlns="http://www.tei-c.org/ns/1.0" target="https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/fMS_C07.xml#,1,2)"/> is invalid
index.js:1375 Pointer <ptr xmlns="http://www.tei-c.org/ns/1.0" target="https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/fMS_C07.xml#,1,24)"/> is invalid

```

Bad pointers in chunk 8:
```
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0017']/tei:zone[@type='left_margin']//tei:line[1] returned more than one node
2
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0020']/tei:zone[@type='left_margin']//tei:line[2] returned more than one node
6
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0022']/tei:zone[@type='left_margin']//tei:line[1] returned more than one node
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0024']/tei:zone[@type='left_margin']//tei:line[1] returned more than one node
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0026']/tei:zone[@type='left_margin']//tei:line[1] returned more than one node
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0026']/tei:zone[@type='left_margin']//tei:line[2] returned more than one node
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0026']/tei:zone[@type='left_margin']//tei:line[3] returned more than one node
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0026']/tei:zone[@type='left_margin']//tei:line[6] returned more than one node
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0026']/tei:zone[@type='left_margin']//tei:line[1] returned more than one node
3
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0029']/tei:zone[@type='left_margin']//tei:line[1] returned more than one node
index.js:1375 Pointer <ptr xmlns="http://www.tei-c.org/ns/1.0" target="https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/fMS_C08.xml#,1,11)"/> is invalid
index.js:1375 Pointer <ptr xmlns="http://www.tei-c.org/ns/1.0" target="https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/fMS_C08.xml#,1,26)"/> is invalid
index.js:1375 Pointer <ptr xmlns="http://www.tei-c.org/ns/1.0" target="https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/fMS_C08.xml#,1,2)"/> is invalid
2
index.js:1375 Pointer <ptr xmlns="http://www.tei-c.org/ns/1.0" target="https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/fMS_C08.xml#,1,19)"/> is invalid
index.js:1375 Pointer <ptr xmlns="http://www.tei-c.org/ns/1.0" target="https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/fMS_C08.xml#,1,2)"/> is invalid
index.js:1375 Pointer <ptr xmlns="http://www.tei-c.org/ns/1.0" target="https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/fMS_C08.xml#,1,3)"/> is invalid
index.js:1375 Pointer <ptr xmlns="http://www.tei-c.org/ns/1.0" target="https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/fMS_C08.xml#,1,5)"/> is invalid
index.js:1375 Pointer <ptr xmlns="http://www.tei-c.org/ns/1.0" target="https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/fMS_C08.xml#,4,6)"/> is invalid
index.js:1375 Pointer <ptr xmlns="http://www.tei-c.org/ns/1.0" target="https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/fMS_C08.xml#,6,14)"/> is invalid
```

Bad pointers in chunk 9:
```
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0031']/tei:zone[@type='left_margin']//tei:line[2] returned more than one node
6
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0032']/tei:zone[@type='left_margin']//tei:line[1] returned more than one node
2
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0032']/tei:zone[@type='left_margin']//tei:line[2] returned more than one node
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0032']/tei:zone[@type='left_margin']//tei:line[3] returned more than one node
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0032']/tei:zone[@type='left_margin']//tei:line[4] returned more than one node
2
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0033']/tei:zone[@type='left_margin']//tei:line[1] returned more than one node
2
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0034']/tei:zone[@type='left_margin']//tei:line[1] returned more than one node
2
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0035']/tei:zone[@type='left_margin']//tei:line[1] returned more than one node
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0035']/tei:zone[@type='left_margin']//tei:line[2] returned more than one node
2
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0035']/tei:zone[@type='left_margin']//tei:line[3] returned more than one node
2
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0038']/tei:zone[@type='left_margin']//tei:line[1] returned more than one node
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0038']/tei:zone[@type='left_margin']//tei:line[2] returned more than one node
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0039']/tei:zone[@type='left_margin']//tei:line[1] returned more than one node
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0039']/tei:zone[@type='left_margin']//tei:line[2] returned more than one node
2
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0039']/tei:zone[@type='left_margin']//tei:line[1] returned more than one node
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0039']/tei:zone[@type='left_margin']//tei:line[2] returned more than one node
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0039']/tei:zone[@type='left_margin']//tei:line[3] returned more than one node
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0039']/tei:zone[@type='left_margin']//tei:line[1] returned more than one node
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0039']/tei:zone[@type='left_margin']//tei:line[3] returned more than one node
6
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0040']/tei:zone[@type='left_margin']//tei:line[1] returned more than one node
4
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0041']/tei:zone[@type='left_margin']//tei:line[1] returned more than one node
4
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0042']/tei:zone[@type='left_margin']//tei:line[1] returned more than one node
﻿
```

Bad pointers in chunk 10:
```
5
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0045']/tei:zone[@type='left_margin']//tei:line[1] returned more than one node
2
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0047']/tei:zone[@type='left_margin']//tei:line[1] returned more than one node
2
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0048']/tei:zone[@type='left_margin']//tei:line[1] returned more than one node
2
index.js:1375 string-range for xpath //tei:surface[@xml:id='ox-ms_abinger_c56-0051']/tei:zone[@type='left_margin']//tei:line[1] returned more than one node
﻿
​
```

**Comment by ebeshero** [comment] 2019-07-04 16:26
@zmbq Thank you for documenting these--and I think we can resolve many of them in C07 quickly. I'm noticing that many of these are pointers going into main lines, and on inspection I find the pointers are correct, but the files we assembled in variorum-chunks actually contain a couple of copies of some of the surfaces(!) If we were pointing directly at the S-GA data, we wouldn't have this problem--I know where the issue arises: it must be in our assemblage of the fMS files from xi:includes locally in this repo--something we did because of the decision against working directly with S-GA files on MITH's repo. Because @raffazizzi isn't available until this weekend and because I'd need his help to fix this properly, I'm doing the next best thing and **commenting out the duplicate surfaces in these files**. 

The even better thing to do, really, is point out to the S-GA files directly again. I can redo the pointers again to point directly to S-GA's individual files representing these page surfaces if that's better. (If it were me, that's what I'd do.) Let me know. In the meantime, I've commented out the repeating surfaces in the fMS C07 file, and pushed that. I'll do the same for the other files in a few minutes.

**Comment by ebeshero** [comment] 2019-07-04 16:36
Okay, that was the problem for a C07, but C08 is okay--no duplicate surfaces...The ambiguities in resolution are to do with left-margin zones, where there are multiple of these, you get multiple line 1's. I think the solution to this is to add a `[contains()]` predicate to resolve these properly, pulling from our normalized tokens. That's some careful XSLT / XPath work, but I think I can do it. Let me see if I can identify what's up with C09 and C10 now.

**Comment by ebeshero** [comment] 2019-07-04 16:48
Okay--C09 and C10 are all left-margin zone issues, as well, and we need to add something, like `[contains(., 'string')]` to pinpoint the correct line because there are multiple left-margin zones. 

(Or we need to be pulling in the xml:id location of the left-margin zone, which is what I was tinkering with last week.) I think the XPath `contains()` or `matches()` function might work for this data.) Want me to give this a try? It may be tricky: the easiest way I know to get some strings to match is from our normalized tokens on the `rdgGrp/@n` in the spine, and I'm not sure of white spaces...thinking out loud I'd probably use `matches()` (which allows regex) and `\s*` in between the first one or two normalized tokens. Some of those tokens contain flattened markup, so I don't want that...`matches()` looks deep through the tree for strings, though, so if could dodge the markup I could search for anything that isn't inside flattened angle brackets, I can probably construct a reasonable match to refine the pointer. In short--this is a little programming challenge, and probably worth doing on the plane--but I can't do it right now. It's also exactly the sort of problem that's interesting to tinker with and talk about in a conference setting.

@zmbq I know that @raffazizzi is coming back online over the weekend and we'd been planning to do some work on importing MS data knowing that we'd hit a wall here. (I'm okay with communicating to people at the conference that this is a point we're working on, and also to discuss *how* we're working on it.) Raff and I will probably want to pick up wherever you leave off on this, and I think I've sketched out a clear path to keep going here.

**Comment by ebeshero** [comment] 2019-07-04 16:50
@zmbq What *should* work now are the pointers to main surface lines in S-GA on C07, now that I've commented out the weirdly repeated cluster of surfaces that were causing duplicate errors there.

**Comment by ebeshero** [comment] 2019-07-04 16:56
@zmbq If C07's main line pointers work again (I don't see any left_margin zones in that chunk), we might have something to show here. There is a small cluster of invalid string pointers, and I'm puzzled about their syntax:

```
index.js:1375 Pointer <ptr xmlns="http://www.tei-c.org/ns/1.0"
 target="https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-
chunks/fMS_C07.xml#,1,2)"/> is invalid
```
What I see is a hashmark in front of a comma, and I'm expecting we need to eliminate the first comma. Is that the issue? If it is, we'll do a quick and easy patch for this...let me know.

**Comment by ebeshero** [comment] 2019-07-04 17:34
Investigating the pointers a little more: 
In the same spine location in C07 (presumably others), we see pointers coming out differently: the first is missing its XPath, but the other two *in the same app location* are just fine: 

```xml
<ptr target=https://raw.githubusercontent.com/PghFrankenstein/
fv-data/master/variorum-chunks/fMS_C07.xml#,1,3)/>

<ptr target=https://raw.githubusercontent.com/PghFrankenstein/
fv-data/master/variorum-chunks/fMS_C07.xml
#string-range(//tei:surface[@xml:id='ox-ms_abinger_c56-0012']/tei:zone[@type='left_margin']//tei:line[1],0,19)/>

<ptr target=https://raw.githubusercontent.com/PghFrankenstein/
fv-data/master/variorum-chunks/fMS_C07.xm
#string-range(//tei:surface[@xml:id='ox-ms_abinger_c56-0012']/tei:zone[@type='left_margin']//tei:line[2],0,5)/>               
```
I should write up a Schematron to check for this phenomenon, and also see why it's happening. I bet it's a conditional statement in the XSLT that's somehow blocking the output of the XPath location in the first case. 

Skimming through the bad pointers output above, I see this phenomenon of *missing XPath location* on C07 and C08.

**Comment by zmbq** [comment] 2019-07-04 18:42
Don't bother with pointers to side notes, we will not be displaying them for now.




I am quite convinced xpaths with string ranges are not the right way to represent differences between editions. Just see how hard we're all working on this. It's not because we're all inadequate, it's because this representation does not fit the problem very well.




Being a relative bystander, and having a general dislike of XML ever since I wrote a DTD back in the 90s, I may have some ideas. But first I need your help to define the problem. You want to model differences, but differences between what? What are you comparing?




I'm not sure it's text, since you have side notes, deletions and additions that are also modeled. Or is it? If one text says "hello" and the other says "hpello" with the p marked as deleted. Is this a difference? If one text says "one two three" and the other says "one two" and "three" in a side note, is that a difference? 




Get Outlook for Android







On Thu, Jul 4, 2019 at 8:34 PM +0300, "Elisa Beshero-Bondar" <notifications@github.com> wrote:












Investigating the pointers a little more:

In the same spine location in C07 (presumably others), we see pointers coming out differently: the first is missing its XPath, but the other two in the same app location are just fine:
<ptr target=https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/fMS_C07.xml#,1,3)/>
<ptr target=https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/fMS_C07.xml#string-range(//tei:surface[@xml:id='ox-ms_abinger_c56-0012']/tei:zone[@type='left_margin']//tei:line[1],0,19)/>
<ptr target=https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/fMS_C07.xml#string-range(//tei:surface[@xml:id='ox-ms_abinger_c56-0012']/tei:zone[@type='left_margin']//tei:line[2],0,5)/>               



I should write up a Schematron to check for this phenomenon, and also see why it's happening. I bet it's a conditional statement in the XSLT that's somehow blocking the output of the XPath location in the first case.

**Comment by ebeshero** [comment] 2019-07-04 21:48
@zmbq Yes, it would constitute a difference, albeit a minor one, in our variorum: We were able successfully to collate markup of deletions and insertions and have that modelled in the collation data. You can see all those in the normalized tokens stored in the spine files.

My sense of how to represent this involves pulling in the normalized tokens we have stored at each app location in each `<rdgGrp>`: that's the raw collation data representing what we have modeled as variation in the project.

**Comment by ebeshero** [comment] 2019-07-04 21:49
In the limited_Spine directory that I output yesterday, I reproduced the collation data for fMS as text strings for the fMS in each spine location. I have hoped it might prove useful.

**Comment by ebeshero** [comment] 2019-07-04 21:51
You may want to read our publications on the subject already if you need to know how we produced the spine. We certainly don't need to reinvent the collation here--it's already complete for these units. And it's possible to reproduce S-GA files from my normalized resequencing of them, stored in this repo as well. We've opted against doing that in real life, but it's not as if, just because we're having trouble generating pointers, that the data isn't there.

**Comment by ebeshero** [comment] 2019-07-04 21:55
See https://www.balisage.net/Proceedings/vol21/html/Beshero-Bondar01/BalisageVol21-Beshero-Bondar01.html .

**Comment by zmbq** [comment] 2019-07-05 06:00
Thanks for the link. I'll read it thoroughly. The first few oagaraphs, quoting people who say TEI is not interoperable seem very true. I once started reading through the TEI guidelines. I stopped when I read that TEI was a recommendation, not a standard, because the committee did not want to tell scholars how to work.




Right then it was clear TEI is going to be a real mess. I could imagine a group of people discussing TEI at the "Final First TEI Guidelines Consortium" , and all but one or two agreeing on how TEI should look. Those two people had their own ideas and wouldn't budge. So the only way out was not to agree on a standard. And now we're all facing the consequences. 




Get Outlook for Android







On Fri, Jul 5, 2019 at 12:55 AM +0300, "Elisa Beshero-Bondar" <notifications@github.com> wrote:












See https://www.balisage.net/Proceedings/vol21/html/Beshero-Bondar01/BalisageVol21-Beshero-Bondar01.html .

**Comment by ebeshero** [comment] 2019-10-06 15:19
Closing because handled a different way in the July 2019 prototype viewer. We'll revisit this elsewhere in updating the spines and postcollation processing.

**Closed as completed by ebeshero** 2019-10-06 15:19 UTC
